name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Configure gcloud
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud config set run/region us-central1

    - name: Debug – Show repo contents
      run: |
        echo "Listing files:"
        ls -la

    - name: Build and push Docker image
      run: |
        IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT }}/adk-agent-${{ github.ref_name }}"
        gcloud builds submit --tag $IMAGE_NAME .



    - name: Deploy to Cloud Run
      run: |
        IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT }}/adk-agent-${{ github.ref_name }}"
        SERVICE_NAME="adk-agent-${{ github.ref_name }}"

        gcloud run deploy $SERVICE_NAME \
          --image $IMAGE_NAME \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
